### ISSUE TITLE
Generating from SQL file doesn't work

### ISSUE THREAD

**Issue by nymann** [nymann/generate-fastapi#31]
```sql
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE tokens (
    token UUID DEFAULT uuid_generate_v4(),
    created TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(token)
);
```

```
$ generate_fastapi --project-name mail_api migrations/versions/added_tokens/upgrade.sql
Target directory [.]: 
[Model(fields=[Field(name='token', field_type=FieldType(name='uuid', max_length=None, min_length=None, nullable=True, default='uuid_generate_v4()'), is_primary_key=True), Field(name='created', field_type=FieldType(name='datetime', max_length=None, min_length=None, nullable=False, default='CURRENT_TIMESTAMP'), is_primary_key=False)], routes=[Route(name='GetList', include=True), Route(name='GetById', include=True), Route(name='Post', include=True), Route(name='Update', include=True), Route(name='DeleteById', include=True)], names=Names(singular_name='token', plural_name='tokens'))]
Folder at: ./src already exists. Using existing folder instead.
Folder at: ./src/mail_api already exists. Using existing folder instead.
Folder at: ./src/mail_api/core already exists. Using existing folder instead.
Folder at: ./src/mail_api/domain already exists. Using existing folder instead.
Folder at: ./src/mail_api/routers already exists. Using existing folder instead.
Folder at: ./tests already exists. Using existing folder instead.
Folder at: ./migrations already exists. Using existing folder instead.
Folder at: ./migrations/versions already exists. Using existing folder instead.
Folder at: ./src/mail_api/domain/tokens already exists. Using existing folder instead.
Folder at: ./tests/test_tokens already exists. Using existing folder instead.
Folder at: ./migrations/versions/added_tokens already exists. Using existing folder instead.
Traceback (most recent call last):
  File "/home/knj/.local/bin/generate_fastapi", line 33, in <module>
    sys.exit(load_entry_point('generate-fastapi==115557rc0', 'console_scripts', 'generate_fastapi')())
  File "/home/knj/.local/lib/python3.8/site-packages/generate_fastapi/__init__.py", line 82, in entry_point
    typer.run(main)
  File "/home/knj/.local/lib/python3.8/site-packages/typer/main.py", line 855, in run
    app()
  File "/home/knj/.local/lib/python3.8/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/knj/.local/lib/python3.8/site-packages/typer/main.py", line 497, in wrapper
    return callback(**use_params)  # type: ignore
  File "/home/knj/.local/lib/python3.8/site-packages/generate_fastapi/__init__.py", line 76, in main
    gen_dirs_and_files(file=file, targetpath=target_directory,
  File "/home/knj/.local/lib/python3.8/site-packages/generate_fastapi/__init__.py", line 50, in gen_dirs_and_files
    FastApiGenerator.gen_api_files(
  File "/home/knj/.local/lib/python3.8/site-packages/generate_fastapi/file_generators/fastapi_generator.py", line 41, in gen_api_files
    _gen_model_domain_files(
  File "/home/knj/.local/lib/python3.8/site-packages/generate_fastapi/file_generators/fastapi_generator.py", line 317, in _gen_model_domain_files
    _gen_domain_model_file(model, templates_path, project_dir, project_name)
  File "/home/knj/.local/lib/python3.8/site-packages/generate_fastapi/file_generators/fastapi_generator.py", line 296, in _gen_domain_model_file
    _gen_model_file(model, template_model_dir, model_dir, project_name)
  File "/home/knj/.local/lib/python3.8/site-packages/generate_fastapi/file_generators/fastapi_generator.py", line 93, in _gen_model_file
    file_content = template.render(
  File "/home/knj/.local/lib/python3.8/site-packages/mako/template.py", line 476, in render
    return runtime._render(self, self.callable_, args, data)
  File "/home/knj/.local/lib/python3.8/site-packages/mako/runtime.py", line 878, in _render
    _render_context(
  File "/home/knj/.local/lib/python3.8/site-packages/mako/runtime.py", line 920, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/home/knj/.local/lib/python3.8/site-packages/mako/runtime.py", line 947, in _exec_template
    callable_(context, *args, **kwargs)
  File "_home_knj__local_lib_python3_8_site_packages_generate_fastapi_mako_templates_src_project_domain_model_template_model_py", line 34, in render_body
  File "/home/knj/.local/lib/python3.8/site-packages/generate_fastapi/translators/json_translator.py", line 42, in translate_field_to_db_dec
    'DB.Column(DB.{1}'.format(
IndexError: Replacement index 1 out of range for positional args tuple
```

**Comment by nymann** [comment]
Resolved
